
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 948366406591-u0nfgdbgimqi0gqrfmnmq28ncno82qt8.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:codebreaker_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
    hibernate:
      ddl-auto: update
server:
  port: 18081
  servlet:
    context-path: /codebreaker